spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB  #Permet de définir la taille d'un fichier lors de téléchargement

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/